attn_only: false
batch_size: 16
color_jitter: 0.3
cooldown_epochs: 0
cutmix: 1.0
data_root: /home/xucao/ASD/datasets/Kaggle_AutismDataset2
drop: 0.0
drop_path: 0.05
epochs: 300
input_size: 224
lr: 1.0e-05
min_lr: 1.0e-06
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: deit3_small_patch16_224
num_classes: 2
num_workers: 4
opt: adamw
sched: cosine
smoothing: 0.0
src: false
three_augment: false
vis_path: ./runs/vis
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
